name: Update Adobe Data

on:
  schedule:
    - cron: '3 */1 * * *' # Runs every 1 hour
  workflow_dispatch:

jobs:
  update-adobe-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set time zone
      run: |
        sudo timedatectl set-timezone America/New_York

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml pytz

    - name: Run generate_adobe_latest.py
      run: python .github/actions/generate_adobe_latest.py

    - name: Run generate_readme.py
      run: python .github/actions/generate_readme.py

    - name: Commit changes
      continue-on-error: true
      env:
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated update by GitHub Actions" || echo "No changes to commit"
        git push https://github-actions[bot]:$TOKEN@github.com/${{ github.repository }}.git
